/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.alrm;

public final class R {
  public static final class color {
    public static final int md_theme_background=0x7f010000;
    public static final int md_theme_dark_background=0x7f010001;
    public static final int md_theme_dark_onPrimary=0x7f010002;
    public static final int md_theme_dark_onPrimaryContainer=0x7f010003;
    public static final int md_theme_dark_onSurface=0x7f010004;
    public static final int md_theme_dark_primary=0x7f010005;
    public static final int md_theme_dark_primaryContainer=0x7f010006;
    public static final int md_theme_dark_surface=0x7f010007;
    public static final int md_theme_error=0x7f010008;
    public static final int md_theme_onError=0x7f010009;
    public static final int md_theme_onPrimary=0x7f01000a;
    public static final int md_theme_onPrimaryContainer=0x7f01000b;
    public static final int md_theme_onSecondary=0x7f01000c;
    public static final int md_theme_onSecondaryContainer=0x7f01000d;
    public static final int md_theme_onSurface=0x7f01000e;
    public static final int md_theme_primary=0x7f01000f;
    public static final int md_theme_primaryContainer=0x7f010010;
    public static final int md_theme_secondary=0x7f010011;
    public static final int md_theme_secondaryContainer=0x7f010012;
    public static final int md_theme_surface=0x7f010013;
  }
  public static final class drawable {
    public static final int fab_bg=0x7f020000;
    public static final int ic_add=0x7f020001;
    public static final int ic_alarm=0x7f020002;
    public static final int ic_dismiss=0x7f020003;
    public static final int ic_settings=0x7f020004;
  }
  public static final class id {
    public static final int action_settings=0x7f030000;
    public static final int btnApr=0x7f030001;
    public static final int btnAug=0x7f030002;
    public static final int btnAutumn=0x7f030003;
    public static final int btnDec=0x7f030004;
    public static final int btnDismiss=0x7f030005;
    public static final int btnFeb=0x7f030006;
    public static final int btnFri=0x7f030007;
    public static final int btnJan=0x7f030008;
    public static final int btnJul=0x7f030009;
    public static final int btnJun=0x7f03000a;
    public static final int btnMar=0x7f03000b;
    public static final int btnMay=0x7f03000c;
    public static final int btnMon=0x7f03000d;
    public static final int btnNov=0x7f03000e;
    public static final int btnOct=0x7f03000f;
    public static final int btnSat=0x7f030010;
    public static final int btnSave=0x7f030011;
    public static final int btnSep=0x7f030012;
    public static final int btnSnooze=0x7f030013;
    public static final int btnSpring=0x7f030014;
    public static final int btnSubmit=0x7f030015;
    public static final int btnSummer=0x7f030016;
    public static final int btnSun=0x7f030017;
    public static final int btnThu=0x7f030018;
    public static final int btnTue=0x7f030019;
    public static final int btnWed=0x7f03001a;
    public static final int btnWinter=0x7f03001b;
    public static final int editAnswer=0x7f03001c;
    public static final int editCalendarKeywords=0x7f03001d;
    public static final int editLabel=0x7f03001e;
    public static final int emptyView=0x7f03001f;
    public static final int fab=0x7f030020;
    public static final int layoutCalendar=0x7f030021;
    public static final int layoutDays=0x7f030022;
    public static final int layoutInput=0x7f030023;
    public static final int layoutMonths=0x7f030024;
    public static final int layoutSeasons=0x7f030025;
    public static final int listView=0x7f030026;
    public static final int progressShake=0x7f030027;
    public static final int seekbarVolume=0x7f030028;
    public static final int sliderMaxSnoozes=0x7f030029;
    public static final int sliderSnoozeDuration=0x7f03002a;
    public static final int spinnerPuzzleType=0x7f03002b;
    public static final int spinnerScheduleType=0x7f03002c;
    public static final int switchEnabled=0x7f03002d;
    public static final int switchVibrate=0x7f03002e;
    public static final int textLabel=0x7f03002f;
    public static final int textPuzzleHint=0x7f030030;
    public static final int textPuzzleQuestion=0x7f030031;
    public static final int textPuzzleSubtitle=0x7f030032;
    public static final int textPuzzleTitle=0x7f030033;
    public static final int textSchedule=0x7f030034;
    public static final int textShakeCount=0x7f030035;
    public static final int textTime=0x7f030036;
    public static final int timePicker=0x7f030037;
  }
  public static final class layout {
    public static final int activity_add_edit_alarm=0x7f040000;
    public static final int activity_alarm_fire=0x7f040001;
    public static final int activity_main=0x7f040002;
    public static final int activity_puzzle=0x7f040003;
    public static final int activity_settings=0x7f040004;
    public static final int item_alarm=0x7f040005;
  }
  public static final class menu {
    public static final int menu_main=0x7f050000;
  }
  public static final class mipmap {
    public static final int ic_launcher=0x7f060000;
    public static final int ic_launcher_round=0x7f060001;
  }
  public static final class string {
    public static final int add_alarm=0x7f070000;
    public static final int alarm_channel_desc=0x7f070001;
    /**
     * Notifications
     */
    public static final int alarm_channel_name=0x7f070002;
    public static final int alarm_deleted=0x7f070003;
    /**
     * Add/edit alarm
     */
    public static final int alarm_label=0x7f070004;
    /**
     * Alarm fire screen
     */
    public static final int alarm_ringing=0x7f070005;
    public static final int app_name=0x7f070006;
    public static final int calendar_keywords=0x7f070007;
    public static final int calendar_keywords_hint=0x7f070008;
    public static final int calendar_permission_required=0x7f070009;
    public static final int dismiss=0x7f07000a;
    public static final int edit_alarm=0x7f07000b;
    public static final int enter_answer=0x7f07000c;
    public static final int enter_digits_no_spaces=0x7f07000d;
    public static final int enter_next_number=0x7f07000e;
    public static final int enter_sequence=0x7f07000f;
    public static final int max_snoozes_label=0x7f070010;
    public static final int memorise_sequence=0x7f070011;
    /**
     * Main screen
     */
    public static final int no_alarms=0x7f070012;
    public static final int no_more_snoozes=0x7f070013;
    public static final int puzzle_type=0x7f070014;
    public static final int save=0x7f070015;
    public static final int schedule_type=0x7f070016;
    public static final int settings=0x7f070017;
    public static final int settings_coming_soon=0x7f070018;
    public static final int shake_phone_puzzle=0x7f070019;
    public static final int snooze_duration_label=0x7f07001a;
    public static final int snooze_solve_puzzle=0x7f07001b;
    public static final int solve_puzzle_to_snooze=0x7f07001c;
    /**
     * Puzzle
     */
    public static final int solve_to_snooze=0x7f07001d;
    public static final int submit=0x7f07001e;
    public static final int tap_to_dismiss=0x7f07001f;
    public static final int undo=0x7f070020;
    public static final int vibrate=0x7f070021;
    public static final int volume=0x7f070022;
    public static final int what_was_the_sequence=0x7f070023;
    public static final int wrong_answer_try_again=0x7f070024;
  }
  public static final class style {
    /**
     * Uses the built-in Material Light theme — no external library required
     */
    public static final int Theme_Alrm=0x7f080000;
  }
}